### ISSUE TITLE
生成uml图出错，用的是test文件夹下的dapps文件

### ISSUE THREAD

**Issue by Evanlai8** [imfly/js2uml#1]
![image](https://cloud.githubusercontent.com/assets/20983292/21250996/bc0c412a-c384-11e6-9e9f-acb545e2e8f2.png)

**Comment by imfly** [comment]
Graphviz 等都安装了吗？

**Comment by xuncanzhe** [comment]
我也是
![image](https://cloud.githubusercontent.com/assets/7651130/24858587/79a537f6-1e1f-11e7-8e0a-1a296843103a.png)
Graphviz 也都装好了

**Comment by larkwins** [comment]
同上，graphviz都好了

```
js2uml -s .\domain.js -o uml.puml
C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:111
            (node.expression.left.name === "exports" ||
                                  ^

TypeError: Cannot read property 'name' of undefined
    at getNodeName (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:111:35)
    at Controller.enter (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:88:23)
    at Controller.__execute (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:397:31)    at Controller.traverse (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:501:28)
    at Object.traverse (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:713:27)
    at Parser (C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:82:16)
    at C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:296:35
    at C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:296:35
    at C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:48:27
    at C:\Users\Yunfan\AppData\Roaming\npm\node_modules\js2uml\lib\index.js:28:24
```
