### ISSUE TITLE
esprima  issue (Error: Line 1: Unexpected token)

### ISSUE THREAD

**Issue by helpsocialbotspy** [imfly/js2uml#5]
helpu@MacBook-Pro:~/Documents/Projects/instagram-private-api$ js2uml -s src/index.ts -o uml.png

/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:5702
            throw e;
            ^
Error: Line 1: Unexpected token
    at constructError (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:2407:21)
    at createError (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:3973:21)
    at parseScriptBody (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/usr/local/lib/node_modules/js2uml/node_modules/esprima/esprima.js:5690:23)
    at Parser (/usr/local/lib/node_modules/js2uml/lib/parser.js:79:24)
    at /usr/local/lib/node_modules/js2uml/node_modules/ramda/dist/ramda.js:296:35

**Comment by Sinica15** [comment]
same problem

**Comment by windyao** [comment]
+1

**Comment by fuchengking** [comment]
+1

**Comment by imfly** [comment]
Sorry，there is no support for typescript. If you are interested, you can extend it.

**Comment by WardPearce** [comment]
I'm receiving this same issue but with plain javascript (using nodejs)

![preview](https://tinyurl.com/ydjozk4z)

**Comment by yeyuguo** [comment]
same problem +1

**Comment by yeyuguo** [comment]
1. 可能是使用了 export 导致会报这个错误
2. 不能使用 扩展操作符

**Comment by gyrate** [comment]
+1

**Comment by gr01** [comment]
+1
