### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by solo14000** [imfly/js2uml#7]
Hi,

I have installed your js2uml npm package from Microsoft Visual Studio Code terminal window.
When trying to run it ajainst a simple JS file, I get the following error

`js2uml -s .\object.js -o  object.png
C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:111
            (node.expression.left.name === "exports" ||
                                  ^

TypeError: Cannot read property 'name' of undefined
    at getNodeName (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:111:35)
    at Controller.enter (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:88:23)
    at Controller.__execute (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:330:31)
    at Controller.traverse (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:434:28)
    at Object.traverse (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\estraverse\estraverse.js:646:27)
    at Parser (C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\lib\parser.js:82:16)
    at C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:296:35
    at C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:296:35
    at C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\node_modules\ramda\dist\ramda.js:48:27
    at C:\Users\asus\AppData\Roaming\npm\node_modules\js2uml\lib\index.js:28:24`

Could you help me ?

Thanks in advance

**Comment by imfly** [comment]
Thank you use js2uml and give me feedback. 😄 

Two reasons：

- 1. I don't test js2uml on windows, so I don't know if win is compatible.
- 2. I don't know your env, e.g: node, npm, and  Graphviz is installed in particular? Please confirm these is right.

**Comment by solo14000** [comment]
I'm using node-v12.18.4-x64
I don't remember installing npm on its own. It seems to be npm 6.14.6
I haven't installed Graphviz.  It may be the cause of my trouble. Could you confim ?

Thanks

**Comment by imfly** [comment]
Make sure you use graphviz！ 😢
